### ISSUE TITLE
Can we analyse the our own data (VCF)?

### ISSUE THREAD

**Issue by vmevada102** [bioforensics/MicroHapDB#152]
This tool represents the excellent details regarding the Haplotypes in Genomes.

I need to understand usage and importance of this tool for analyse our own data present in VCF tool. 

Can we analyse our dat with tools used for the buiding this databas?

Kindly suggest tools and script to analyse our own data.

**Comment by standage** [comment]
Greetings @vmevada102! 👋 

The data in MicroHapDB is collected from a variety of published sources. The MicroHapDB software doesn't perform any microhaplotype *discovery*, it serves merely as a data warehouse for microhaps that have already been discovered.

To learn more about microhaplotype discovery, I'd recommend reading some of the papers cited on [this page](https://microhapdb.readthedocs.io/en/latest/citations.html#published-marker-collections-and-allele-frequency-data).
