### ISSUE TITLE
Jin 2020

### ISSUE THREAD

**Issue by standage** [bioforensics/MicroHapDB#86]
## Paper

Jin XY, Cui W, Chen C, Guo YX, Zhang XR, Xing GH, Lan JW, Zhu BF (2020) Developing and population analysis of a new multiplex panel of 18 microhaplotypes and compound markers using next generation sequencing and its application in the Shaanxi Han population. *Electrophoresis*, **41**(13-14):1230-1237, [doi:10.1002/elps.201900451](https://doi.org/10.1002/elps.201900451).

## Data URL(s)

https://doi.org/10.1002/elps.201900451 Table 1

## Author and PI information

Bo-Feng Zhu

**Comment by rnmitchell** [comment]
Do you have the full version of this paper? I'm running into a paywall. If not, I'll email Jason Harrington.

**Comment by standage** [comment]
Attached to the email I sent to you, Dane, and Ryan.

**Comment by standage** [comment]
Closed by #89.
