### ISSUE TITLE
Suggestion: Add `-y` when installing `pytest` in README

### ISSUE THREAD

**Issue by danejo3** [bioforensics/MicroHapDB#93]
Just wanted to add a small suggestion for the README file. 

After the user creates their own Conda environment called, `microhapdb`, the user can copy-paste the following two lines.

>conda install pytest
pytest --pyargs microhapdb --doctest-modules

When a users copy-pastes these lines into the terminal, the terminal will execute the first line but will hang up on, "Does the user want to proceed downloading these packages.. (y/n): etc." and will not execute `pytest` until the users says yes. To streamline the execution, we could add the `-y` in the first command so that way it automatically says yes to the incoming packages and then immediately execute pytest when downloaded.

> conda install pytest -y

**Comment by standage** [comment]
Thank you, that's an astute observation and a great suggestion!
